const { OpenAI } = require('openai');
const Diagnosis = require('../models/diagnosis.model');

// Initialize OpenAI client
const openai = new OpenAI();

/**
 * Service to handle Diagnosis business logic and DB communication.
 */
exports.createDiagnosis = async (symptoms) => {
    // 1. Prompt Engineering: Give the AI strict persona, rules, and output format instructions.
    const prompt = `You are a medical AI assistant.
A user reported the following symptoms: "${symptoms}".

Analyze these symptoms and provide the top 2 possible underlying conditions.
You MUST output the result strictly as a valid, raw JSON array of objects. DO NOT include markdown text formatting like \`\`\`json. DO NOT include pleasantries.
Each object in the array must contain EXACTLY the following keys:
- "condition": The name of the possible condition.
- "probability": A percentage indicating the likelihood (e.g., "80%").
- "suggested_next_steps": Suggested next steps such as tests to run or type of doctor to consult.

Example format:
[
  {
    "condition": "Common Cold",
    "probability": "75%",
    "suggested_next_steps": "Rest, stay hydrated, and consult a General Physician if symptoms persist."
  }
]`;

    try {
        // 2. Call OpenAI API
        const completion = await openai.chat.completions.create({
            model: "gpt-4o-mini", // Fast, accurate, and cost-effective model
            messages: [{ role: "user", content: prompt }],
            temperature: 0.3, // Lower temperature makes it more factual and strict
        });

        // 3. Parse the structured JSON output generated by the AI
        const aiResponseText = completion.choices[0].message.content.trim();
        const generatedResult = JSON.parse(aiResponseText);

        // 4. Save the structured result into the database
        const newDiagnosis = await Diagnosis.create({
            symptoms: symptoms,
            result: generatedResult
        });

        return newDiagnosis;
    } catch (error) {
        console.error("OpenAI Quota/Logic Error, falling back to Rule-Based system:", error.message);
        
        // 5. HYBRID FALLBACK: If OpenAI quota is exceeded, use intelligent rule-based mapping
        let fallbackConditions = [];
        const lowerSymptoms = symptoms.toLowerCase();
        
        if (lowerSymptoms.includes('fever') && lowerSymptoms.includes('cough')) {
            fallbackConditions.push({ condition: "Viral Infection", probability: "85%", suggested_next_steps: "Rest, monitor temperature, and consult a doctor if fever lasts > 3 days." });
            fallbackConditions.push({ condition: "Common Cold", probability: "60%", suggested_next_steps: "Stay hydrated and take over-the-counter medicine." });
        } else if (lowerSymptoms.includes('headache') || lowerSymptoms.includes('nausea')) {
            fallbackConditions.push({ condition: "Tension Headache / Migraine", probability: "70%", suggested_next_steps: "Reduce screen time, rest in a quiet, dark room." });
        } else {
            fallbackConditions.push({ condition: "General Malaise", probability: "50%", suggested_next_steps: "Observe symptoms closely. Consult a General Physician if conditions worsen." });
        }

        const newDiagnosis = await Diagnosis.create({
            symptoms: symptoms,
            result: fallbackConditions
        });
        
        return newDiagnosis;
    }
};

/**
 * Fetch all diagnosis history from the database.
 * Supports sorting by provided order, defaults to newest first.
 */
exports.getDiagnosisHistory = async (sortOrder = 'desc') => {
    // Determine the sorting method (-1 is descending, 1 is ascending)
    const order = sortOrder === 'asc' ? 1 : -1;
    
    // Find all records and sort them by createdAt automatically
    const history = await Diagnosis.find().sort({ createdAt: order });
    
    return history;
};
